version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: app-backend
    ports:
      - "8080:8080" # предполагаем, что Go-приложение слушает 8080
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: app-frontend
    ports:
      - "80:80" # nginx по умолчанию
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
