services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: app-backend
    ports:
      - "8081:8081"  # Align with app's port
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    environment:
      - APP_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8081/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: app-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  app-network:
    driver: bridge

volumes:
  backend-data: