services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: app-backend
    ports:
      - "8081:8081"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    environment:
      - APP_ENV=production
      - PORT=8081
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: app-frontend
    ports:
      - "80:8080"
    restart: unless-stopped
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VUE_APP_API_URL=/api

    security_opt:
      - no-new-privileges:true
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  app-network:
    driver: bridge

volumes:
  backend-data: