version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: app-backend
    ports:
      - "8080:8080" # предполагаем, что Go-приложение слушает 8080
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: app-frontend
    ports:
      - "80:80" # nginx по умолчанию
    restart: unless-stopped
    tmpfs:
      - /tmp
      - /var/cache/nginx
    security_opt:
      - no-new-privileges:true
    read_only: true