name: Docker Project Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        id: backend_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: false
          tags: backend:ci

      - name: Scan backend with Trivy
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          image-ref: backend:ci
          ignore-unfixed: true
          format: table
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest


      - name: Build frontend image
        id: frontend_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          push: false
          tags: frontend:ci

      - name: Scan frontend with Trivy
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          image-ref: frontend:ci
          ignore-unfixed: true
          format: table
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest